mysite/main/urls.py
from django.urls import path
from django.urls.resolvers import URLPattern
from . import views, service

urlpatterns = [
    path("author/<str:authorId>/posts/<str:postId>", views.userMoment, name = "userMoment"),
    path("home/", views.home, name = "home"),
    path("create/", views.home, name = "create"),
    path("view/", views.view, name="view"),
    path("register/", views.register, name="register"),
    path("author/<str:id>", views.userCenter, name="userCenter"),
    path("messageBox/", views.messageBox, name="messageBox"),
    path("following/", views.following, name="following"),
    path("userCenterEdit/", views.userCenterEdit, name="userCenterEdit"),
    path("friendRequest/<str:selfId>/<str:otherId>", views.friendRequest, name="friendRequest"),
    path("unfollow/<str:otherId>", views.unfollow, name="unfollow"),
    path("author/<str:id>/inbox/", views.inbox, name="inbox"),
    path("momentEdit/<str:postId>", views.momentEdit, name="MomentEdit"),
    path("author/<str:authorId>/posts/", views.doMoment, name = "doMoment"),
    path("author/<str:authorId>/posts/<str:postId>/comments", views.createComment, name = "createComment"),
    path("author/<str:id>/commentLike/", views.inbox, name = "commentLike"),
    path("author/<str:authorId>/posts/<str:postId>/edit", views.momentEdit, name = "momentEdit"),
    path("author/<str:authorId>/posts/<str:postId>/share", views.momentRepost, name = "momentRepost"),
    path("getFriend/", views.getFriend, name = "getFriend"),
    # path("get/form/<str:formType>", views.getForm, name="getForm")
    path("remotePost/detail/", views.remotePostDetail, name = "remotePostDetail"),
    path("remoteUser/detail/", views.remoteUserDetail, name = "remoteUserDetail"),
    path("browseAuthors/", views.browseAuthors, name="broseAuthors"),
    path("author/<str:authorId>/githubFlow", views.githubFlow, name="githubFlow"),
    path("author/<str:authorId>/posts/<str:postId>/comments/<str:commentId>/", views.commentToPost, name="commentToPost"),
    path("", views.redirectToHome, name = "redirectToHome"),
    path("remote/<int:team>/author/<str:authorId>/posts", views.remoteAuthorPosts, name="remoteAuthorPosts"),

    path("author/<str:userId>/addProfileImage/", views.addProfileImage, name="addProfileImage"),
    


    # GET: retrieve all profiles on the server paginated
    path("service/authors/", service.retrive_user_all, name="retrive_user_all"), 

    # GET: retrieve their profile
    # POST: update profile
    path("service/author/<str:author_id>/", service.retrive_user, name="retrive_user"),
    
    # GET: get a list of authors who are their followers
    path("service/author/<str:author_id>/followers", service.retrive_followers, name="retrive_followers"),
    
    # DELETE: remove a follower
    # PUT: Add a follower (must be authenticated)
    # GET check if follower
    path("service/author/<str:author_id>/followers/<str:foreign_author_id>", service.manage_followers, name="manage_followers"),

    # GET get the public post
    # POST update the post (must be authenticated)
    # DELETE remove the post
    # PUT create a post with that post_id
    path("service/author/<str:author_id>/posts/<str:post_id>", service.manage_posts, name="manage_posts"),

    # GET get recent posts of author (paginated)
    # POST create a new post but generate a post_id
    path("service/author/<str:author_id>/posts/", service.do_posts, name="do_posts"),


    # GET get comments of the post
    # POST if you post an object of “type”:”comment”, it will add your comment to the post
    path("service/author/<str:author_id>/posts/<str:post_id>/comments", service.manage_comments, name="manage_comments"),

    # GET: if authenticated get a list of posts sent to {AUTHOR_ID}
    # POST: send a post to the author
    # if the type is “post” then add that post to the author’s inbox
    # if the type is “follow” then add that follow to the author’s inbox to approve later
    # if the type is “like” then add that like to the author’s inbox
    # DELETE: clear the inbox
    path("service/author/<str:author_id>/inbox/", service.send_inbox, name="send_likes"),

    # GET a list of likes from other authors on author_id’s post post_id
    path("service/author/<str:author_id>/posts/<str:post_id>/likes", service.get_likes_post, name="get_likes_post"),

    # GET a list of likes from other authors on author_id’s post post_id comment comment_id
    path("service/author/<str:author_id>/posts/<str:post_id>/comments/<str:comment_id>/likes", service.get_likes_comment, name="get_likes_comment"),

    # GET list what public things author_id liked
    path("service/author/<str:author_id>/liked", service.get_liked, name="get_liked"),

]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("main.urls")),
    path('', include("django.contrib.auth.urls")),
    
]

mysite/main/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
#from django.db.models import constraints
import uuid
# from django.conf import settings
def createUUID():
    return str(uuid.uuid4())
# Create your models here.

class User(AbstractUser):
    type = models.CharField(max_length=2000, null=True)
    id = models.CharField(max_length=2000, primary_key=True, default=createUUID)
    localId = models.CharField(max_length=2000, null=True)
    host = models.CharField(max_length=2000, null=True)
    displayName = models.CharField(max_length=2000, null=True)
    url = models.URLField(max_length=2000, null=True)
    github = models.URLField(max_length=2000, null=True)
    profileImage = models.URLField(max_length=2000, null=True)
    authorized = models.BooleanField(default=False)

class Pending(models.Model):
    pendingUser = models.ForeignKey("User", on_delete=models.CASCADE, related_name="pending",null=True)
    type = models.CharField(max_length=2000, default="pending user")   


class Moment(models.Model):
    type = models.CharField(max_length=2000, null=True)
    title = models.CharField(max_length=2000, null=True)
    id = models.CharField(max_length=2000, primary_key=True)
    localId = models.CharField(max_length=2000)
    source = models.CharField(max_length=2000, null=True)
    origin = models.CharField(max_length=2000, null=True)
    description = models.CharField(max_length=2000, null=True)
    contentType = models.CharField(max_length=2000, null=True)
    content = models.CharField(max_length=10485760, null=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="moment", null=True)
    categories = models.JSONField(null=True)
    count = models.PositiveIntegerField(null=True)
    comments = models.URLField(null=True)
    commentsSrc = models.JSONField(null=True)
    published = models.CharField(max_length=2000,null=True)
    visibility = models.CharField(max_length=2000,null=True)
    unlisted = models.BooleanField(null=True)
    def __str__(self):
        return self.content

class Comment(models.Model):
    moment = models.ForeignKey(Moment, on_delete=models.CASCADE, null=True)
    type = models.CharField(max_length=2000, null=True)
    author =  models.ForeignKey(User, on_delete=models.CASCADE, related_name="comment", null=True)
    content = models.CharField(max_length=2000, null=True)
    contentType = models.CharField(max_length=2000, null=True)
    published = models.CharField(max_length=2000,null=True)
    commentId = models.CharField(max_length=2000, null=True)
    localId = models.CharField(max_length=2000, null=True)
    remote = models.BooleanField(default=False)
    remote_author = models.JSONField(null=True)

    def __str__(self):
        return self.content


class Likes(models.Model):

    context = models.URLField()
    summary = models.CharField(max_length=2000)
    type = models.CharField(max_length=2000)
    author = models.JSONField()
    object = models.URLField()
    userId = models.CharField(max_length=2000)
    class Meta:
        constraints = [
            models.UniqueConstraint(fields= ['userId','object'], name="like constraint")
        ]

class Liked(models.Model):
    type = models.CharField(max_length=2000)
    itmes = models.JSONField()

class Following(models.Model):
    user = models.ForeignKey("User", on_delete=models.CASCADE, related_name="following")
    following_user = models.ForeignKey("User", on_delete=models.CASCADE, related_name="followed")
    class Meta:
        constraints = [
            models.UniqueConstraint(fields= ['user','following_user'], name="follow constraint")
        ]

class Inbox(models.Model):
    type = models.CharField(max_length=2000)
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name="inbox", null=True)
    items = models.JSONField()

mysite/main/forms.py
from django import forms
from django.contrib.auth import login, authenticate
from django.contrib.auth.forms import UserCreationForm
from django.db.models import fields
from .models import User, Moment
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Fieldset, ButtonHolder, Submit
import datetime




class CreateNewMoment(forms.ModelForm):

    
    title = forms.CharField(label="title", max_length=2000, 
                                widget=forms.TextInput({
                                    'class':'form-control',
                                    'placeholder':'Title'
                                }), required=True)
    content = forms.CharField(label="content", max_length=10485760,
                             widget=forms.Textarea({
                                    'class':'form-control',
                                    'placeholder':'Content'
                                }), required=False)
    CHOICES= (
    ('Public','Public'),
    ('Friend','Friend'),
    ('Unlisted','Unlisted')
    )
    CHOICES2= (
    ('text/plain', 'plain text'),
    ('text/markdown', 'markDown'),
    ('application/base64', 'application'),
    ('image/jpeg;base64', 'JPEG'),
    ('image/png;base64', 'PNG'),
    )
    visibility = forms.ChoiceField(widget=forms.Select, choices=CHOICES)
    contentType = forms.ChoiceField(widget=forms.Select, choices=CHOICES2)
    fileSelect = forms.FileField(label='fileSelect', required=False)

    class Meta:
        model = Moment
        fields = {"title", 'content',  'visibility', 'contentType', 'fileSelect'}
    

class RegisterForm(UserCreationForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ["username", "email", "password1", "password2"]


class UserProfileEdit(forms.ModelForm):
    
    username = forms.CharField()
    email = forms.EmailField()
    github = forms.CharField()
    class Meta:
        model = User
        fields = ["username", "email", "github"]

mysite/main/templates/main/aPostList.html
{% extends 'main/base.html' %}


{% block title %}
View
{% endblock %}

{% block style %}
<style>
#submitButton {
    margin-top: 10pt;
    margin-bottom: 5pt;
    margin-left: 10pt;
    float: right;
}
</style>
{% endblock %}



{% block content %}
    <script>
        var contentBody;
        var counter = 0;
        var src = '{{content | safe}}';

        src = JSON.parse(src);
        console.log(src);

        function addImage(contentBody){
            let img = new Image();
            img.src = src[counter];
            // console.log(img.src);
            contentBody.appendChild(img);
            contentBody.setAttribute('style', 'display:flex; justify-content: center');
        }
    </script>
    {% for pl in showList %}
    <div class="moment" style="margin-top:40pt;">
        
        <div class="card ">
            <div class="card-header">
                Posted by  <a href="{{pl.user.id}}">{{pl.user.displayName}}</a>
                <br>
                At:{{pl.published}}
                <br>
                Title:{{pl.title}}
            </div>
            
            <div class="card-body"><a id="content-body" href="{{pl.id}}"></a></div>

            {% if pl.contentType == "image/jpeg;base64" or pl.contentType == "image/png;base64" or pl.contentType == "application/base64" %}
              <script type="text/javascript">
                  contentBody = [...document.querySelectorAll('#content-body')][counter];
                  
                  addImage(contentBody);
                  counter += 1;
              </script>
            {% else %}
                <script type="text/javascript">
                    contentBody = [...document.querySelectorAll('#content-body')][counter];
                    contentBody.innerHTML = src[counter];
                    counter += 1;
                </script>
            {% endif %}
        </div>
    </div> 
    {% endfor %}
    
    <form method="get" action="/author/{{authorId}}/posts/" class="form-group">
        {% csrf_token %}
          {% if page == maxPage %}
          <input id="submitButton" class="btn btn-primary" type="submit" value="Next page" disabled> 
        {% else %}

          <input type="hidden" name="page" value={{page|add:1}}>
          <input type="hidden" name="size" value={{size}}>
          <input type="hidden" name="type" value="next">
          <input id="submitButton" class="btn btn-primary" type="submit" value="Next page"> 
        {%endif%}
    </form>

    <form method="get" action="/author/{{authorId}}/posts/" class="form-group">
        {% csrf_token %}
        {% if page == 1 %}
        <input id="submitButton" class="btn btn-primary" type="submit" value="Previous page" disabled> 
        {% else %}
        <input type="hidden" name="page" value={{page|add:-1}}>
        <input type="hidden" name="size" value={{size}}>
        <input type="hidden" name="type" value="previous">
        <input id="submitButton" class="btn btn-primary" type="submit" value="Previous page"> 
        {%endif%}


    </form>



{% endblock %}

mysite/main/templates/main/aPostListRemote.html
{% extends 'main/base.html' %}


{% block title %}
View
{% endblock %}

{% block style %}
<style>
#submitButton {
    margin-top: 10pt;
    margin-bottom: 5pt;
    margin-left: 10pt;
    float: right;
}
</style>
{% endblock %}

{% block content %}

    <div class="old" style="margin-top:40pt;">
        
        <div class="card ">
            <div class="card-header">
                Posted by  <a href="#"></a>
                <br>
                At:
                <br>
                Title:
            </div>
            
            <div class="card-body"><a id="content-body" href="#"></a></div>
        </div>
    </div> 
    

    <script>
        let team = '{{team}}';
        let id = '{{id}}';
        let url;
        if (team == 10){
            url = "https://social-distribution-t10.herokuapp.com/api/author/" + id + '/posts/';
        }else if(team == 18){
            url = "https://cmput404-socialdistributio-t18.herokuapp.com/author/" + id + '/posts/';
        }
        
        let req = new Request(url);
        fetch(req)
        .then(response => response.json())
        .then(data => {
            let postData = data["data"];
            let oldDiv = document.querySelector(".old");
            for (let post of postData){
                let newDiv = document.createElement("div");
                newDiv.innerHTML = oldDiv.innerHTML;
                newDiv.setAttribute("style","margin-top:40pt;");
                newDiv.setAttribute("class", "moment");
                oldDiv.parentElement.appendChild(newDiv);

                let heading = newDiv.children[0].children[0];
                let body = newDiv.children[0].children[1];
                // let buttons = newDiv.children[1];

                // let shareButton = buttons.children[0];
                // let commentButton = buttons.children[1];
                // let likeButton = buttons.children[2];

                // likeButton.herf = "#";
                // likeUrlT10 = post["author"]["id"] + "/inbox/";
                // objectUrlT10 = post["source"];
                // likeButton.setAttribute("onclick", 'sendLike(likeUrlT10, objectUrlT10)');
                // // likeButton.addEventListener('click', sendLike(url10 + "author/" + post["author"]["id"] + "/inbox/"));
                

                newForm1 = document.createElement("form")
                newForm1.setAttribute("action","/remoteUser/detail/")
                newForm1.setAttribute("method","post")
                profileButton = document.createElement("button")

                authorName = post["author"]['displayName']
                profileButton.innerText = "Posted by " + authorName
                profileButton.setAttribute("class", "btn btn-link btoa")
                profileButton.setAttribute("role", "link")

                profileButton.setAttribute("type","submit")
                hiddenValue1 = document.createElement("input")
                hiddenValue1.setAttribute("type", "hidden")
                hiddenValue1.setAttribute("name", "data")
                hiddenValue1.setAttribute("value", JSON.stringify(post['author']))

                newForm1.appendChild(profileButton)
                newForm1.appendChild(hiddenValue1)
                newForm1.innerHTML += '{% csrf_token %}'
                

                heading.removeChild(heading.children[1])
                heading.appendChild(newForm1)

                

                newForm = document.createElement("form")
                newForm.setAttribute("action","/remotePost/detail/")
                newForm.setAttribute("method","post")
                titleButton = document.createElement("button")
                titleButton.setAttribute("class", "btn btn-link btoa")
                titleButton.setAttribute("role", "link")


                titleButton.innerText = post["title"]
                titleButton.setAttribute("type","submit")
                hiddenValue = document.createElement("input")
                hiddenValue.setAttribute("type", "hidden")
                hiddenValue.setAttribute("name", "data")
                hiddenValue.setAttribute("value", JSON.stringify(post))

                newForm.appendChild(titleButton)
                newForm.appendChild(hiddenValue)
                newForm.innerHTML += '{% csrf_token %}'

                newDiv1 = document.createElement("div")
                newDiv1.textContent = "At: " + post["published"];


                heading.innerHTML = ''

                heading.appendChild(newForm1)
                heading.appendChild(newDiv1)
                heading.appendChild(newForm)

                let text = post["contentType"];

                let temp = body.children[0];
                    if (temp){
                    temp.parentElement.removeChild(temp);
                    }
                if (['application/base64', 'image/png;base64', 'image/jpeg;base64'].includes(text)){
                    
                    let img = new Image();
                    img.src = post["content"];
                    body.appendChild(img);
                }else{
                    body.textContent = post["content"];
                    body.setAttribute("style", "");
                }
            }
            oldDiv.innerHTML = '';
            let pervButton = document.createElement('a');
            let nextButton = document.createElement('a');
            pervButton.setAttribute("id", "submitButton");
            nextButton.setAttribute("id", "submitButton");
            pervButton.value 
            oldDiv.parentElement.appendChild(pervButton);
            oldDiv.parentElement.appendChild(nextButton);
        })

        
    </script>
{% endblock %}

mysite/main/templates/main/base.html
<!doctype html>
<html lang="en">
    <head>
        {% block style %}{% endblock %}
        <style type="text/css">
            
            .sidenav {
               overflow: hidden;
               background-color: #333;
               position: fixed;
               top: 0;
               width: 100%;
               z-index: 100;
            }

            .sidenav a {
                float: left;
                display: block;
                color: #f2f2f2;
                text-align: center;
                padding: 14px 16px;
                text-decoration: none;
            }

            .sidenav a:hover {
                background: #ddd;
                color:black;
            }

            .main {
                margin-top: 80px;
            }
            #id_visibility{
                width: auto;
            }
            
            #id_content{
                height: 100px;
            }
            title{
                text-align: center;
            }
            .card-body{
                word-wrap: break-word;
            }
            img{
                width: 20em;
            }
            .selector-for-some-widget {
                box-sizing: content-box;
            }

            pre {
                display: block !important;
                padding: 9.5px  !important;
                margin: 0 0 10px  !important;
                font-size: 13px  !important;
                line-height: 1.42857143  !important;
                color: #333  !important;
                word-break: break-all  !important;
                word-wrap: break-word  !important;
                background-color: #f5f5f5 !important;
                border: 1px solid #ccc !important;
                border-radius: 4px !important;
            }
        </style>
        <!-- Required meta tags -->

        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        
        <!-- <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">  -->
        <!-- <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css"> -->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

        <title>{% block title %}{% endblock %}</title>
    </head>

    <body>
        <div class="sidenav">
            <a href="/home">Home</a>          
            {%if user.is_anonymous%}
            <a href="/login" style="float: right;">Login</a>
            {%elif not user.authorized %}
            <a href="/logout/" style="float: right;">Logout</a>
            {%else%}
            <a href="/view">Post</a>
            <a href="/author/{{user.localId}}/inbox/" >Inbox</a>
            <a href="/browseAuthors" >Browse Authors</a>
            <a href="/logout/" style="float: right;">Logout</a>
            <a href="/author/{{user.localId}}" style="float: right;">{{user.displayName}}</a>
            {%endif%}

        </div>
        <div id="content", name="content", class="main"> 
            <div class="row justify-content-center">
                <div class="col-8">
                    <h2 class="mt-0" style="text-align: center; margin-left: auto; margin-right: auto;">Glowing Palm Tree</h2>
                    <hr class="mt-0 mb-4" style="margin-left: auto; margin-right: auto;">
                    {% block content %}
                    {% endblock %}
                    </div>
            </div>
        </div>

        <!-- Optional JavaScript -->
        <!-- jQuery first, then Popper.js, then Bootstrap JS -->
        <!-- <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script> -->

        <!-- <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script> -->
        <!-- <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script> -->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/showdown/1.9.0/showdown.min.js"></script>
    </body>
</html>

mysite/main/templates/main/create.html
{% extends 'main/base.html' %}


{% block title %}
Create new post
{% endblock %}

{% load crispy_forms_tags %}

{% block content %}
<h3>Create Page</h3>
<form method="post" action="/create/" class="form-group">
    {% csrf_token %}
    {{form|crispy}}
    <input id="post" type="submit" value="submit">
</form>
{% endblock %}

mysite/main/templates/main/home.html
{% extends 'main/base.html' %}

{% block style %}
<style>
  a.buttons{
    font-size: x-large;
    padding-left: 10px;
    padding-right: 10px;
    display: flex;
    justify-content: center;
    align-items: center;
  }
  a.username{
    
    padding-left: 0;
    padding-right: 0;
  }
  .form-check-label {
    margin-bottom: 0;
    margin-left: 10pt;
  }
  #submitButton {
    float: right;
  }
  #id_contentType{
    width: auto;
  }
  #div_id_fileSelect{
    display: none;
  }
  label {
    width: 70pt;
  }
</style>
{% endblock %}
{% block title %}
Create new post


{% endblock %}

{% load crispy_forms_tags %}
{% load custom_tags %}
{% block content %}

  {% if user.is_anonymous%}
    <a href="/login/" class="btn btn-primary buttons">Login To Share Your Posts!</a>
  
  {% elif not user.authorized %}
  <h1 style="text-align: center;">Your registration is still in process.</h1>

  {%else%}
  
    <h3>Create Post</h3>
    <form method="post" action="{{user.id}}/posts/" class="form-group" id="contentForm" onsubmit="post()">
        {% csrf_token %}
        {{form|crispy}}
          <br>
          <fieldset>  
            <legend>Categories</legend>  
            <div class="btn-group" role="group" aria-label="Basic checkbox toggle button group">
              <input type="checkbox" class="btn-check" id="btncheck1" autocomplete="off" name="Categories" value="Food" >
              <label class="btn btn-outline-secondary" for="btncheck1">Food</label>
              <input type="checkbox" class="btn-check" id="btncheck2" autocomplete="off" name="Categories" value="News" > 
              <label class="btn btn-outline-secondary" for="btncheck2">News</label>
              <input type="checkbox" class="btn-check" id="btncheck4" autocomplete="off" name="Categories" value="Business">
              <label class="btn btn-outline-secondary" for="btncheck4">Business</label>
              <input type="checkbox" class="btn-check" id="btncheck6" autocomplete="off" name="Categories" value="Sports">
              <label class="btn btn-outline-secondary" for="btncheck6">Sports</label>
              <input type="checkbox" class="btn-check" id="btncheck8" autocomplete="off" name="Categories" value="Games"> 
              <label class="btn btn-outline-secondary" for="btncheck8">Games</label>
              <input type="checkbox" class="btn-check" id="btncheck9" autocomplete="off" name="Categories" value="ACG"> 
              <label class="btn btn-outline-secondary" for="btncheck9">ACG</label>
            </div>
          </fieldset>
          <input id="submitButton" class="btn btn-primary" type="submit" value="Post" style="margin-top: 30pt;">  
    </form>
  {%endif%}
<br>
<br>

<script>
  var contentBody;
  var counter = 0;
  var src = '{{content | safe}}';

  src = JSON.parse(src);
  src = src["content"]

  function addImage(contentBody){
    let img = new Image();
    img.src = src[counter];
    // console.log(img.src);
    contentBody.appendChild(img);
    contentBody.setAttribute('style', 'display:flex; justify-content: center');
  }
</script>
  {% if user.is_anonymous or not user.authorized%}
  
    {% for pl in moments%}
      <div class="moment" style="margin-top:40pt;">
        <div class="card ">
          <div class="card-header">
            {% if user.is_anonymous%}
            Posted by  <a href="/login">{{pl.user.displayName}}</a>
            {% else %}
            Posted by  <a href="{{pl.user.id}}">{{pl.user.displayName}}</a>

            {%endif%}

            <br>
            At:{{pl.published}}
            <br>
            Title:{{pl.title}}
          </div>
          <div class="card-body" id="content-body"></div>
          {% if pl.contentType == "image/png;base64" or pl.contentType == "image/jpeg;base64" or pl.contentType == "application/base64" %}
            <script type="text/javascript">

                contentBody = [...document.querySelectorAll('#content-body')][counter];
                addImage(contentBody);
                counter += 1;
            </script>
          {% else %}
            <script type="text/javascript">
              contentBody = [...document.querySelectorAll('#content-body')][counter];
              contentBody.innerHTML = src[counter];
              counter += 1;
            </script>
          {% endif %}
        </div>  
      </div>
      
    {% endfor %}
  {%endif%}
<script>

  var typeSelector = document.getElementById("id_contentType");


  let contentDiv = document.getElementById("div_id_content");
  let img = document.createElement("img");
  img.setAttribute('id', 'image');
  contentDiv.appendChild(img);

  let fileSelector = document.getElementById("id_fileSelect");

  typeSelector.addEventListener('change', function () {
    let text = typeSelector.value;
    if (['application/base64', 'image/png;base64', 'image/jpeg;base64'].includes(text)){
      
      let fileSelector = document.getElementById('div_id_fileSelect');
      fileSelector.setAttribute('style', 'display:block');
      form = document.getElementById('contentForm');
      form.appendChild(fileSelector);

      let contentBox = document.getElementById("id_content");
      contentBox.setAttribute('style', 'display:none');
    }
    else{
      let fileSelector = document.getElementById('div_id_fileSelect');
      fileSelector.setAttribute('style', 'display:none');

      let contentBox = document.getElementById("id_content");
      contentBox.setAttribute('style', 'display:block');
    }
  });

  fileSelector.onchange = e => {
    const [file] = fileSelector.files;
    if (file) {
    img.src = URL.createObjectURL(file);
    }
    var reader = new FileReader();

    let file1 = fileSelector.files;
    reader.readAsDataURL(file1[0]);

    reader.onload = function () {
      let contentBox = document.getElementById("id_content");
      contentBox.value = reader.result;
    };

  }
  // changeForm();
</script>



{% endblock %}